[package]
name = "vaultcore"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10"
argon2 = "0.5"
rand_core = { version = "0.6", features = ["std"] }
zeroize = { version = "1", features = ["derive"] }
thiserror = "1"
hkdf = "0.12"
sha2 = "0.10"
x25519-dalek = { version = "2", features = ["static_secrets"] }
ml-kem = "0.2"
serde = { version = "1", features = ["derive"] }
bincode = "1"
aes-siv = "0.7"
base64 = "0.22"
clap = { version = "4", features = ["derive"] }
rpassword = "7"
libc = "0.2"
zip = { version = "2", default-features = false, features = ["deflate", "aes-crypto"] }

[target.'cfg(all(unix, not(target_os = "android")))'.dependencies]
fuser = "0.14"

[dev-dependencies]
tempfile = "3"
